# We are using the iOS build system to create Mac OS X python builds
language: objective-c

before_install:
  # OS extra info
  - uname -a
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"

  # Install python
  - brew update
  - brew install python 
  - brew link --overwrite python
  - pip install --upgrade pip
  - PATH=/usr/local/bin:$PATH
  - echo $PATH
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"

  - brew install libcouchbase

  - pip install mock

  # Install node.js
  - brew unlink node
  - brew install node
  - node --version
  - npm --version

# Build and Pack ardublockly
install:
  #- cd package/pyinstaller/bootloader
  #- python ./waf configure build install
  #- cd ../../../
  - python package/build_pyinstaller.py mac
  - cd package/electron
  - npm install
  - npm run release
  - cd ../..
  - python package/pack_ardublockly.py
  - du -sk releases/

# For now only running a known passing test, the others need to be updated
script:
  - python ardublocklyserver/tests/sketchcreator_test.py
  - python ardublocklyserver/tests/compilersettings_test.py

# Deploy the build version in an S3 bucket
deploy:
  provider: s3
  access_key_id: AKIAIBDOPX6GSMBDEFPQ
  secret_access_key:
    secure: QNNNIgHpcTYJZS1K4w8iPqJWq1Xhx8ICoVJ79QURS5Vi4ppnP0smuW13+XdmjoZyoceSoR4iOcKX7o4HXDozsejy3ft72tXgNntVQoOOKYxnV1zKYHc7Q6ID6L3GlPKV2EQid30CM4bP0mm4P8ntuemUOwhqm4mjRwDxAMpxsEbXgNAHAMifn40g5u2rHuwo64+UUll6m2Ues6mekAlwq6YQKn0numrcHRZX9F3kMLyrSHO671EkyfVsBbZpk7+HIEXmgXgPb4juefcxUlhYQFvnlBPyyTG1ec0BE2un714vZe+Gq0w1UYQbIpsAvM1HDWQKa2S9m2gz1TXC5YXOKAfoenyFsrgvdT00zpxVrTLAGhmIgtxsbAYXVPRg/6g5E+DW/JJ2xBfMJyw3j/82vexkHpvQcut9zZ74CE2H0CtyNXHvwdcwMs+qoja6tLw1dvFD7yrTo2T/jCOxFoGYjneF3Syuh8GpALSGGUJDnyFiK0yD2B0r2567csFj5Sc0CO/ExFwfG9zmiVtkm0Xpfq09VcZFjVnJ4k8QyNvrHmnGB/H7P6CskSA1X9gGIyk36Cu17XyyrtIuM+UUIdnrZhWCI3zA/2UVawkEjA+zhpbKFKsxIe37bPpIpNM+OyMLppZzzpcaRAynh6a/8Hcc+ckh4zMg7qWu7VXyYvjSkl0=
  bucket: ardublockly-builds
  skip_cleanup: true
  local-dir: releases
  upload-dir: mac
  acl: public_read
  on:
    repo: carlosperate/ardublockly
    branch: [master, travisci, electron]

notifications:
  email:
    on_success: change
    on_failure: change
